# -*- coding: utf-8 -*-
"""sudoku_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnN2--TjhVxths37gYsVRjMcSW066jsI
"""

import random
import time
import copy
import matplotlib.pyplot as plt


def print_board(board):
    for r in range(9):
        if r % 3 == 0 and r != 0:
            print("-" * 21)

        row = []
        for c in range(9):
            if c % 3 == 0 and c != 0:
                row.append("|")

            if board[r][c] == 0:
                row.append(".")
            else:
                row.append(str(board[r][c]))

        print(" ".join(row))


def is_valid(board, row, col, num):
    for c in range(9):
        if board[row][c] == num:
            return False

    for r in range(9):
        if board[r][col] == num:
            return False

    start_row = (row // 3) * 3
    start_col = (col // 3) * 3

    for r in range(start_row, start_row + 3):
        for c in range(start_col, start_col + 3):
            if board[r][c] == num:
                return False

    return True


def find_empty_basic(board):
    for r in range(9):
        for c in range(9):
            if board[r][c] == 0:
                return r, c

    return None


def solve_basic(board):
    empty = find_empty_basic(board)

    if empty is None:
        return True

    row, col = empty

    for num in range(1, 10):
        if is_valid(board, row, col, num):
            board[row][col] = num

            if solve_basic(board):
                return True

            board[row][col] = 0

    return False


def get_candidates(board, row, col):
    candidates = []

    for num in range(1, 10):
        if is_valid(board, row, col, num):
            candidates.append(num)

    return candidates


def find_empty_mrv(board):
    best_cell = None
    best_candidates = None

    for r in range(9):
        for c in range(9):
            if board[r][c] == 0:
                candidates = get_candidates(board, r, c)

                if len(candidates) == 0:
                    return r, c, []

                if best_candidates is None or len(candidates) < len(best_candidates):
                    best_cell = (r, c)
                    best_candidates = candidates

    if best_cell is None:
        return None

    return best_cell[0], best_cell[1], best_candidates


def solve_mrv(board):
    empty = find_empty_mrv(board)

    if empty is None:
        return True

    row, col, candidates = empty

    if len(candidates) == 0:
        return False

    for num in candidates:
        board[row][col] = num

        if solve_mrv(board):
            return True

        board[row][col] = 0

    return False

def solve_random(board):
    empty = find_empty_mrv(board)

    if empty is None:
        return True

    row, col, candidates = empty
    random.shuffle(candidates)

    for num in candidates:
        board[row][col] = num

        if solve_random(board):
            return True

        board[row][col] = 0

    return False


def generate_full_board():
    board = [[0 for _ in range(9)] for _ in range(9)]
    solve_random(board)
    return board

def count_solutions(board, limit=2):
    count = 0

    def backtrack():
        nonlocal count

        if count >= limit:
            return

        empty = find_empty_mrv(board)

        if empty is None:
            count += 1
            return

        row, col, candidates = empty

        for num in candidates:
            board[row][col] = num
            backtrack()
            board[row][col] = 0

            if count >= limit:
                return

    backtrack()
    return count

def generate_puzzle(difficulty="medium"):
    full_board = generate_full_board()
    puzzle = copy.deepcopy(full_board)

    difficulty_levels = {
        "easy": 35,
        "medium": 45,
        "hard": 55
    }

    numbers_to_remove = difficulty_levels.get(difficulty, 45)

    cells = [(r, c) for r in range(9) for c in range(9)]
    random.shuffle(cells)

    removed = 0

    for row, col in cells:
        if removed >= numbers_to_remove:
            break

        backup = puzzle[row][col]
        puzzle[row][col] = 0

        temp_board = copy.deepcopy(puzzle)

        if count_solutions(temp_board) == 1:
            removed += 1
        else:
            puzzle[row][col] = backup

    return puzzle, full_board


def benchmark_solver(puzzle):
    board_basic = copy.deepcopy(puzzle)
    board_mrv = copy.deepcopy(puzzle)

    start = time.perf_counter()
    solve_basic(board_basic)
    basic_time = time.perf_counter() - start

    start = time.perf_counter()
    solve_mrv(board_mrv)
    mrv_time = time.perf_counter() - start

    return basic_time, mrv_time


def benchmark_difficulties():
    difficulties = ["easy", "medium", "hard"]

    basic_times = []
    mrv_times = []

    for difficulty in difficulties:
        print("\nGenerating", difficulty, "puzzle...")

        puzzle, _ = generate_puzzle(difficulty)

        basic_time, mrv_time = benchmark_solver(puzzle)

        basic_times.append(basic_time)
        mrv_times.append(mrv_time)

        print(difficulty.capitalize(), "completed.")
        print("Basic:", round(basic_time, 6), "seconds")
        print("MRV:", round(mrv_time, 6), "seconds")

    plt.figure(figsize=(8, 5))
    plt.plot(difficulties, basic_times, marker="o", label="Basic Backtracking")
    plt.plot(difficulties, mrv_times, marker="o", label="MRV Heuristic")

    plt.title("Sudoku Solver Performance Comparison")
    plt.xlabel("Difficulty Level")
    plt.ylabel("Solving Time (seconds)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()


def main():
    difficulty = "medium"

    puzzle, _ = generate_puzzle(difficulty)

    print("Generated Sudoku Puzzle:")
    print_board(puzzle)

    print("\nSolution:")
    solved_board = copy.deepcopy(puzzle)
    solve_mrv(solved_board)
    print_board(solved_board)

    print("\nChecking number of solutions:")
    solution_count = count_solutions(copy.deepcopy(puzzle))
    print("Number of solutions:", solution_count)

    print("\nPerformance comparison for one puzzle:")
    basic_time, mrv_time = benchmark_solver(puzzle)

    print("Basic Backtracking Time:", round(basic_time, 6), "seconds")
    print("MRV Heuristic Time:", round(mrv_time, 6), "seconds")

    print("\nBenchmarking all difficulty levels:")
    benchmark_difficulties()


if __name__ == "__main__":
    main()